.TH _PRINTF 1 _printf\-0.1
.SH NAME
_printf \- 
.SH SYNOPSIS
.B _printf
.RB FORMAT
.IR [ARGUMENT]
.RB ...
.SH DESCRIPTION
.B _printf
is a print function that permit us to print any char or a variable of type int, char or str
.RB \\\%\%	produce a single \% 
.SH RETURN VALUE
.B _printf 
return the number of char printed
.SH EXEMPLES
.RB _printf("I love printf");
.P
.RB _printf("%d, %i", i, numb);
.SH AUTHOR
.RB Written by Gaetan Pineiro & Dulker Cesur.